#!/usr/bin/env bash
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#bash
ln -sf ${BASEDIR}/bashrc ~/.bashrc
ln -sf ${BASEDIR}/profile ~/.profile
ln -sf ${BASEDIR}/bash_profile ~/.bash_profile

# vim
ln -sf ${BASEDIR}/vimrc ~/.vimrc
#ln -s ${BASEDIR}/vim/ ~/.vim

# zsh
ln -sf ${BASEDIR}/zshrc ~/.zshrc

# git
#ln -s ${BASEDIR}/gitconfig ~/.gitconfig
